title: 💻 WendellTMO 📄
logo: /assets/img/logo.jpg
description: °If you have any further question, feel free to email me. I'll be glad to answer.°
show_downloads:
google_analytics:
theme: jekyll-theme-minimal
